import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const userId = (session.user as { id: string }).id;
    const { searchParams } = new URL(req.url);
    const jobId = searchParams.get("jobId");
    const format = searchParams.get("format") || "json";

    if (!jobId) {
      return NextResponse.json({ error: "Job ID required" }, { status: 400 });
    }

    const job = await prisma.repurposingJob.findFirst({
      where: { id: jobId, userId },
      include: { content: true },
    });

    if (!job) {
      return NextResponse.json({ error: "Job not found" }, { status: 404 });
    }

    const socialPosts = job.content.filter((c) => c.type === "social_post");
    const newsletter = job.content.find((c) => c.type === "newsletter");
    const videoScript = job.content.find((c) => c.type === "video_script");
    const summary = job.content.find((c) => c.type === "summary");

    if (format === "pdf") {
      const pdfContent = generatePDFContent(job, socialPosts, newsletter, videoScript, summary);
      return new NextResponse(pdfContent, {
        headers: {
          "Content-Type": "text/html",
          "Content-Disposition": `attachment; filename="repurpose-${jobId}.html"`,
        },
      });
    }

    if (format === "docx") {
      const docxContent = generateDocxContent(job, socialPosts, newsletter, videoScript, summary);
      return new NextResponse(docxContent, {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="repurpose-${jobId}.docx"`,
        },
      });
    }

    return NextResponse.json({
      job: {
        id: job.id,
        inputType: job.inputType,
        status: job.status,
        createdAt: job.createdAt.toISOString(),
      },
      socialPosts: socialPosts.map((p) => ({ platform: p.platform, content: p.content })),
      newsletter: newsletter?.content || null,
      videoScript: videoScript?.content || null,
      summary: summary?.content || null,
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: "Failed to export" }, { status: 500 });
  }
}

function generatePDFContent(job: any, socialPosts: any[], newsletter: any, videoScript: any, summary: any) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Repurpose Export - ${job.id}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    h1 { color: #d97706; border-bottom: 2px solid #f59e0b; padding-bottom: 10px; }
    h2 { color: #1a1a25; margin-top: 30px; }
    .platform-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; color: white; margin-bottom: 10px; }
    .twitter { background: #1DA1F2; }
    .linkedin { background: #0077B5; }
    .facebook { background: #4267B2; }
    .instagram { background: #E1306C; }
    .content-section { background: #f8fafc; padding: 20px; border-radius: 10px; margin: 15px 0; white-space: pre-wrap; }
    .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
    hr { border: none; border-top: 1px solid #eee; margin: 30px 0; }
  </style>
</head>
<body>
  <h1>Content Repurposing Export</h1>
  <p class="meta">Job ID: ${job.id} | Created: ${new Date(job.createdAt).toLocaleDateString()} | Status: ${job.status}</p>
  
  ${socialPosts.length > 0 ? `
  <h2>Social Media Posts (${socialPosts.length})</h2>
  ${socialPosts.map((p) => `
    <div class="content-section">
      <span class="platform-badge ${p.platform}">${p.platform?.toUpperCase()}</span>
      <p>${p.content}</p>
    </div>
  `).join("")}` : ""}
  
  ${newsletter ? `
  <hr>
  <h2>Newsletter</h2>
  <div class="content-section">${newsletter.content}</div>
  ` : ""}
  
  ${videoScript ? `
  <hr>
  <h2>Video Script</h2>
  <div class="content-section">${videoScript.content}</div>
  ` : ""}
  
  ${summary ? `
  <hr>
  <h2>Summary</h2>
  <div class="content-section">${summary.content}</div>
  ` : ""}
  
  <hr>
  <p style="text-align: center; color: #999; font-size: 12px;">Generated by Repurpose AI</p>
</body>
</html>`;
}

function generateDocxContent(job: any, socialPosts: any[], newsletter: any, videoScript: any, summary: any) {
  return `CONTENT REPURPOSING EXPORT
===============================

Job ID: ${job.id}
Created: ${new Date(job.createdAt).toLocaleDateString()}
Status: ${job.status}

===============================
SOCIAL MEDIA POSTS
===============================

${socialPosts.map((p, i) => `[${(p.platform || "social").toUpperCase()} #${i + 1}]
${p.content}

---`).join("\n")}

${newsletter ? `
===============================
NEWSLETTER
===============================

${newsletter.content}

` : ""}${videoScript ? `
===============================
VIDEO SCRIPT
===============================

${videoScript.content}

` : ""}${summary ? `
===============================
SUMMARY
===============================

${summary.content}

` : ""}
===============================
Generated by Repurpose AI
===============================`;
}